### ISSUE TITLE
[FR]: Ability to kill states as a service

### ISSUE THREAD

**Issue by narsaw** [travisghansen/hass-opnsense#135]
Back when I used pfsense, the HA custom integration I used provided a way to call as a service something like this:

```
service: pfsense.kill_states
data:
    entity_id: binary_sensor.pfsense01_pending_notices_present
    source: 192.168.47.174
```

This allowed me to kill states that belong to certain IP that I wanted to disconnect from the internet in HA.

Can this be done using this custom integration with OPNSENES?
