### ISSUE TITLE
[Bug]: WireGuard Client names missing

### ISSUE THREAD

**Issue by o0shojo0o** [travisghansen/hass-opnsense#299]
### What happened?

Under the sensor `sensor.opnsense_wireguard_server_<servername>_status` the name of the client is missing in the attribute `client`.

### hass-opnsense Version

v0.3.8-beta.3

### OPNsense Firmware

24.7.7-amd64

### Home Assistant Version

2024.10.4

### Additional Details

v0.3.8-beta.3
```
clients: 
- endpoint: 192.168.0.182:61595
  tunnel_addresses:
    - 10.0.0.2/32
  latest_handshake: '2024-10-26T10:45:44+02:00'
  bytes_recv: 286949458
```

v0.3.7
```
clients: 
xxxxxxxx:
  name: Dennis.iPhone
  enabled: true
  pubkey: xxxxxxxx
  tunnel_addresses:
    - 10.0.0.2/32
  endpoint: 192.168.0.182:61595
  bytes_recv: 286949458
  bytes_sent: 2289328120
  latest-handshake: '2024-10-26T10:45:44+02:00'
```
