### ISSUE TITLE
[Bug]: Boottime is "changed" on updates while maintaining the same value

### ISSUE THREAD

**Issue by eopo** [travisghansen/hass-opnsense#378]
### What happened?

The entity _boottime is frequently updated as expected. The retrieved value is set as a new value, which triggers a state_changed event (and subsequently would trigger automations, creates log entries, generates a new color for state graphs)
It would most likely be better to check if the new value equals the old value and decide on that comparison, if the state should be set

### hass-opnsense Version

0.3.16

### OPNsense Firmware

25.1.5_1

### Home Assistant Version

2025.4.2

### Relevant logs

```shell

```

**Comment by alexdelprete** [comment]
Home Assistant's state machine is designed to only trigger a `state_changed` event when there is an actual change in the state value or attributes. If you update an entity to the same state value with the same attributes, no `state_changed` event will be generated, and data will not be recorded.

Did you check if `state_changed` event is fired every X seconds (data update coordinator cycle) for that entity? I checked my HA production instance, waited for some data update cycle, and it doesn't fire, as expected.

**Comment by alexdelprete** [comment]
If you want to easily check, you can use this in the dev tools template section:

```yaml
- Last Updated: {{ states.sensor.opnsense_system_boottime.last_updated }}
- Last Changed: {{ states.sensor.opnsense_system_boottime.last_changed }}
-Last Reported: {{ states.sensor.opnsense_system_boottime.last_reported }}
```

You will see this:

```console
- Last Updated: 2025-04-14 12:46:07.266239+00:00
- Last Changed: 2025-04-14 12:46:07.266239+00:00
-Last Reported: 2025-04-14 17:43:43.339671+00:00
```

And if you wait a polling cycle, and refresh the page, you'll notice that `last_updated` and `last_changed` remain the same, but `last_reported` changes because it is reported by the integration, but the state machine didn't record it since the value (the state) was the same, and so the `state_changed` event is not fired.

```console
- Last Updated: 2025-04-14 12:46:07.266239+00:00
- Last Changed: 2025-04-14 12:46:07.266239+00:00
-Last Reported: 2025-04-14 17:48:11.122017+00:00
```
